---
- name: Remove LXC, snapd in case it's installed (Ubuntu Cloud has it)
  apt:
    state: absent
    pkg:
      - lxc
      - lxd
      - snapd

- name: Upgrade whole system
  apt:
    upgrade: full

- name: Install admin essentials
  apt:
    state: latest
    pkg:
      - mc
      - htop
      - unrar
      - rar
      - zip
      - p7zip
      - curl
      - python3-certbot-nginx
      - systemd-coredump
      - gdb
      - ncdu
 
- name: Create otsmanager system user
  user:
    name: otsmanager
    password: $6$e8gmLzXM.YGXKz$L5YwwV8FitP1WGZQoVTH.1mUcOyFGe7HbYxhl2jJS7a05D1BIsjxUgfxRcjTwGd9riy6w1bqfRCjIq53WN3Kh.
    update_password: on_create
    shell: /bin/bash
    groups: systemd-journal
    append: yes

- name: Select editor for otsmanager
  copy:
    dest: /home/otsmanager/.selected_editor
    content: "SELECTED_EDITOR=\"/usr/bin/mcedit\""
    owner: otsmanager
    group: otsmanager

- name: Install .otsmanager shell configuration
  template:
    src: templates/.otsmanager
    dest: /home/otsmanager/.otsmanager
    owner: otsmanager
    group: otsmanager
    mode: 0644

- name: Activate .otsmanager shell configuration file
  lineinfile:
    dest: /home/otsmanager/.bashrc
    line: . ~/.otsmanager
    regexp: ^\. ~/\.otsmanager

- name: Delete Ubuntu Cloud ad
  file:
    path: /etc/update-motd.d/51-cloudguest
    state: absent

- name: Install welcome message
  template:
    src: templates/61-otshosting-motd
    dest: /etc/update-motd.d/61-otshosting-motd
    owner: root
    group: root
    mode: 0755
