---
- name: 'Compatibility: Install packages needed to compile old TFS (0.3/0.4)'
  apt:
    state: latest
    pkg:
      - autoconf
      - libxml2-dev
      - libboost-thread-dev
      - libboost-regex-dev
      - libboost-filesystem-dev
      - liblua5.1-dev
      - libcrypto++-dev
      - libssl-dev
      - libgmp-dev
